# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0002_remove_user_course_link'),
        ('courses', '0002_usercourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourses',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='courselinks',
            field=models.ManyToManyField(related_name='courselinks', to='user_reg.User'),
        ),
        migrations.DeleteModel(
            name='UserCourses',
        ),
    ]
